export const ADD_POKEMON_DATA = "ADD_POKEMON_DATA";
export const ADD_POKEMON_NAMES = "ADD_POKEMON_NAMES";
export const ADD_POKEMON_TYPES = "ADD_POKEMON_TYPES";
export const TOGGLE_POKEMON_LOAD = "TOGGLE_POKEMON_LOAD";
export const TOGGLE_COLLECTION = "TOGGLE_COLLECTION";
export const ADD_TO_COLLECTION = "ADD_TO_COLLECTION";
export const SET_COLLECTION = "GET_COLLECTION";